//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameConfigure.proto
/*
namespace Com.Lost.GameData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameConfigure")]
  public partial class GameConfigure : global::ProtoBuf.IExtensible
  {
    public GameConfigure() {}
    
    private bool _isFirstGameTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isFirstGameTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFirstGameTime
    {
      get { return _isFirstGameTime; }
      set { _isFirstGameTime = value; }
    }
    private int _nextSpaceId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nextSpaceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nextSpaceId
    {
      get { return _nextSpaceId; }
      set { _nextSpaceId = value; }
    }
    private byte[] _spaceMapMatrix;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"spaceMapMatrix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] spaceMapMatrix
    {
      get { return _spaceMapMatrix; }
      set { _spaceMapMatrix = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
*/

using System.Collections.Generic;
using System.Collections;
using ID_MAP = System.String;
using JsonFx.Json;
using System;

namespace Com.Lost.GameData {
    [System.Serializable]
    public class GameConfigure {
        public GameConfigure() { }

        public SpaceFileItem[] SpaceMapMatrix = new SpaceFileItem[ConstantParams.spaceMatrixSize];
        public bool IsFirstGameTime;
        public SpaceFileItem nextSpace;
    }

    [System.Serializable]
    public class SpaceFileItem{
        public ID_MAP id;
        public string fileName;        
    }
    
}

